[[redirects]]
  from = "/api/*"
  to = "https://api.football-data.org/v4/:splat"
  status = 200
  force = true
  headers = {X-Auth-Token = "c24eb6d142cc4b42a529bed2b380d7db"}


  [[redirects]]
  from = "/fpl-api/*"
  to = "https://fantasy.premierleague.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/fpl-api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/fpl-api/*"
  to = "https://fantasy.premierleague.com/api/:splat"
  status = 200
  force = true


  [build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"



  # Configuration for Netlify Functions
[functions]
  directory = "netlify/functions"

# Redirect /api/fpl to the actual function
[[redirects]]
  from = "/api/fpl"
  to = "/.netlify/functions/fpl-proxy"
  status = 200
  force = true
